//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountUtil.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cn.jdd/services/account", ConfigurationName="AccountService.ACCOUNT")]
    public interface ACCOUNT {
        
        // CODEGEN: 操作 heartBeat 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.heartBeatResponse1 heartBeat(AccountUtil.AccountService.heartBeatRequest1 request);
        
        // CODEGEN: 操作 lastVersion 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.lastVersionResponse1 lastVersion(AccountUtil.AccountService.lastVersionRequest1 request);
        
        // CODEGEN: 操作 personHeartBeat 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.personHeartBeatResponse1 personHeartBeat(AccountUtil.AccountService.personHeartBeatRequest1 request);
        
        // CODEGEN: 操作 accountLogin 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.accountLoginResponse1 accountLogin(AccountUtil.AccountService.accountLoginRequest1 request);
        
        // CODEGEN: 操作 chargedProduct 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.chargedProductResponse1 chargedProduct(AccountUtil.AccountService.chargedProductRequest1 request);
        
        // CODEGEN: 操作 activationLogin 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.activationLoginResponse1 activationLogin(AccountUtil.AccountService.activationLoginRequest1 request);
        
        // CODEGEN: 操作 dayProductComsume 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AccountUtil.AccountService.dayProductComsumeResponse1 dayProductComsume(AccountUtil.AccountService.dayProductComsumeRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class heartBeatRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AccProMacInfo heartBeatRequestInfoField;
        
        /// <remarks/>
        public AccProMacInfo heartBeatRequestInfo {
            get {
                return this.heartBeatRequestInfoField;
            }
            set {
                this.heartBeatRequestInfoField = value;
                this.RaisePropertyChanged("heartBeatRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class AccProMacInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNoField;
        
        private string productCodeField;
        
        private string machineCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("accountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string machineCode {
            get {
                return this.machineCodeField;
            }
            set {
                this.machineCodeField = value;
                this.RaisePropertyChanged("machineCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class DayProductComsume : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productNameField;
        
        private string productCodeField;
        
        private string dayMachineCountField;
        
        private string dayComsumeMoneyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dayMachineCount {
            get {
                return this.dayMachineCountField;
            }
            set {
                this.dayMachineCountField = value;
                this.RaisePropertyChanged("dayMachineCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dayComsumeMoney {
            get {
                return this.dayComsumeMoneyField;
            }
            set {
                this.dayComsumeMoneyField = value;
                this.RaisePropertyChanged("dayComsumeMoney");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class DayProductComsumeResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMsgField;
        
        private DayProductComsume[] dayProductComsumeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dayProductComsume", IsNullable=false)]
        public DayProductComsume[] dayProductComsumeList {
            get {
                return this.dayProductComsumeListField;
            }
            set {
                this.dayProductComsumeListField = value;
                this.RaisePropertyChanged("dayProductComsumeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class DayProductComsumeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("accountNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class AcvResultLoginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMsgField;
        
        private string deadLineField;
        
        private string noticeTitleField;
        
        private string noticeContentField;
        
        private string showFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string deadLine {
            get {
                return this.deadLineField;
            }
            set {
                this.deadLineField = value;
                this.RaisePropertyChanged("deadLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string noticeTitle {
            get {
                return this.noticeTitleField;
            }
            set {
                this.noticeTitleField = value;
                this.RaisePropertyChanged("noticeTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string noticeContent {
            get {
                return this.noticeContentField;
            }
            set {
                this.noticeContentField = value;
                this.RaisePropertyChanged("noticeContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string showFlag {
            get {
                return this.showFlagField;
            }
            set {
                this.showFlagField = value;
                this.RaisePropertyChanged("showFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class AcvLoginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string activationCodeField;
        
        private string productCodeField;
        
        private string machineCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string activationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("activationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string machineCode {
            get {
                return this.machineCodeField;
            }
            set {
                this.machineCodeField = value;
                this.RaisePropertyChanged("machineCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productCodeField;
        
        private string productNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class ChargedProductResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMsgField;
        
        private Product[] productListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("product", IsNullable=false)]
        public Product[] productList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
                this.RaisePropertyChanged("productList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class ChargedProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNoField;
        
        private string passwordField;
        
        private string machineCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("accountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string machineCode {
            get {
                return this.machineCodeField;
            }
            set {
                this.machineCodeField = value;
                this.RaisePropertyChanged("machineCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class His : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productCodeField;
        
        private string comsumeMoneyField;
        
        private string comsumeTimeField;
        
        private string comsumeScoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string comsumeMoney {
            get {
                return this.comsumeMoneyField;
            }
            set {
                this.comsumeMoneyField = value;
                this.RaisePropertyChanged("comsumeMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string comsumeTime {
            get {
                return this.comsumeTimeField;
            }
            set {
                this.comsumeTimeField = value;
                this.RaisePropertyChanged("comsumeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string comsumeScore {
            get {
                return this.comsumeScoreField;
            }
            set {
                this.comsumeScoreField = value;
                this.RaisePropertyChanged("comsumeScore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class ResultLoginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMsgField;
        
        private string comsumeStatusField;
        
        private string balanceField;
        
        private string usableScoreField;
        
        private string disableScoreField;
        
        private string rankNameField;
        
        private string noticeTitleField;
        
        private string noticeContentField;
        
        private string showFlagField;
        
        private His[] comHisListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string comsumeStatus {
            get {
                return this.comsumeStatusField;
            }
            set {
                this.comsumeStatusField = value;
                this.RaisePropertyChanged("comsumeStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string usableScore {
            get {
                return this.usableScoreField;
            }
            set {
                this.usableScoreField = value;
                this.RaisePropertyChanged("usableScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string disableScore {
            get {
                return this.disableScoreField;
            }
            set {
                this.disableScoreField = value;
                this.RaisePropertyChanged("disableScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string rankName {
            get {
                return this.rankNameField;
            }
            set {
                this.rankNameField = value;
                this.RaisePropertyChanged("rankName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string noticeTitle {
            get {
                return this.noticeTitleField;
            }
            set {
                this.noticeTitleField = value;
                this.RaisePropertyChanged("noticeTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string noticeContent {
            get {
                return this.noticeContentField;
            }
            set {
                this.noticeContentField = value;
                this.RaisePropertyChanged("noticeContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string showFlag {
            get {
                return this.showFlagField;
            }
            set {
                this.showFlagField = value;
                this.RaisePropertyChanged("showFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comHis", IsNullable=false)]
        public His[] comHisList {
            get {
                return this.comHisListField;
            }
            set {
                this.comHisListField = value;
                this.RaisePropertyChanged("comHisList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class LoginInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNoField;
        
        private string productCodeField;
        
        private string machineCodeField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("accountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string machineCode {
            get {
                return this.machineCodeField;
            }
            set {
                this.machineCodeField = value;
                this.RaisePropertyChanged("machineCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class AcvProMacInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string activationCodeField;
        
        private string productCodeField;
        
        private string machineCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string activationCode {
            get {
                return this.activationCodeField;
            }
            set {
                this.activationCodeField = value;
                this.RaisePropertyChanged("activationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string machineCode {
            get {
                return this.machineCodeField;
            }
            set {
                this.machineCodeField = value;
                this.RaisePropertyChanged("machineCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class LastVersionResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMsgField;
        
        private string updateVersionUrlField;
        
        private string updateVersionTitleField;
        
        private string updateVersionContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string updateVersionUrl {
            get {
                return this.updateVersionUrlField;
            }
            set {
                this.updateVersionUrlField = value;
                this.RaisePropertyChanged("updateVersionUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string updateVersionTitle {
            get {
                return this.updateVersionTitleField;
            }
            set {
                this.updateVersionTitleField = value;
                this.RaisePropertyChanged("updateVersionTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string updateVersionContent {
            get {
                return this.updateVersionContentField;
            }
            set {
                this.updateVersionContentField = value;
                this.RaisePropertyChanged("updateVersionContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class LastVersionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productCodeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cn.jdd/services/account")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string resultMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class heartBeatResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo heartBeatResponseInfoField;
        
        /// <remarks/>
        public ResultInfo heartBeatResponseInfo {
            get {
                return this.heartBeatResponseInfoField;
            }
            set {
                this.heartBeatResponseInfoField = value;
                this.RaisePropertyChanged("heartBeatResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class heartBeatRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.heartBeatRequest heartBeatRequest;
        
        public heartBeatRequest1() {
        }
        
        public heartBeatRequest1(AccountUtil.AccountService.heartBeatRequest heartBeatRequest) {
            this.heartBeatRequest = heartBeatRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class heartBeatResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.heartBeatResponse heartBeatResponse;
        
        public heartBeatResponse1() {
        }
        
        public heartBeatResponse1(AccountUtil.AccountService.heartBeatResponse heartBeatResponse) {
            this.heartBeatResponse = heartBeatResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class lastVersionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LastVersionInfo lastVersionRequestInfoField;
        
        /// <remarks/>
        public LastVersionInfo lastVersionRequestInfo {
            get {
                return this.lastVersionRequestInfoField;
            }
            set {
                this.lastVersionRequestInfoField = value;
                this.RaisePropertyChanged("lastVersionRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class lastVersionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LastVersionResultInfo lastVersionResponseInfoField;
        
        /// <remarks/>
        public LastVersionResultInfo lastVersionResponseInfo {
            get {
                return this.lastVersionResponseInfoField;
            }
            set {
                this.lastVersionResponseInfoField = value;
                this.RaisePropertyChanged("lastVersionResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lastVersionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.lastVersionRequest lastVersionRequest;
        
        public lastVersionRequest1() {
        }
        
        public lastVersionRequest1(AccountUtil.AccountService.lastVersionRequest lastVersionRequest) {
            this.lastVersionRequest = lastVersionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lastVersionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.lastVersionResponse lastVersionResponse;
        
        public lastVersionResponse1() {
        }
        
        public lastVersionResponse1(AccountUtil.AccountService.lastVersionResponse lastVersionResponse) {
            this.lastVersionResponse = lastVersionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class personHeartBeatRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AcvProMacInfo personHeartBeatRequestInfoField;
        
        /// <remarks/>
        public AcvProMacInfo personHeartBeatRequestInfo {
            get {
                return this.personHeartBeatRequestInfoField;
            }
            set {
                this.personHeartBeatRequestInfoField = value;
                this.RaisePropertyChanged("personHeartBeatRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class personHeartBeatResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo personHeartBeatResponseInfoField;
        
        /// <remarks/>
        public ResultInfo personHeartBeatResponseInfo {
            get {
                return this.personHeartBeatResponseInfoField;
            }
            set {
                this.personHeartBeatResponseInfoField = value;
                this.RaisePropertyChanged("personHeartBeatResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class personHeartBeatRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.personHeartBeatRequest personHeartBeatRequest;
        
        public personHeartBeatRequest1() {
        }
        
        public personHeartBeatRequest1(AccountUtil.AccountService.personHeartBeatRequest personHeartBeatRequest) {
            this.personHeartBeatRequest = personHeartBeatRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class personHeartBeatResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.personHeartBeatResponse personHeartBeatResponse;
        
        public personHeartBeatResponse1() {
        }
        
        public personHeartBeatResponse1(AccountUtil.AccountService.personHeartBeatResponse personHeartBeatResponse) {
            this.personHeartBeatResponse = personHeartBeatResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class accountLoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoginInfo loginRequestInfoField;
        
        /// <remarks/>
        public LoginInfo loginRequestInfo {
            get {
                return this.loginRequestInfoField;
            }
            set {
                this.loginRequestInfoField = value;
                this.RaisePropertyChanged("loginRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class accountLoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultLoginInfo loginResponseInfoField;
        
        /// <remarks/>
        public ResultLoginInfo loginResponseInfo {
            get {
                return this.loginResponseInfoField;
            }
            set {
                this.loginResponseInfoField = value;
                this.RaisePropertyChanged("loginResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountLoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.accountLoginRequest accountLoginRequest;
        
        public accountLoginRequest1() {
        }
        
        public accountLoginRequest1(AccountUtil.AccountService.accountLoginRequest accountLoginRequest) {
            this.accountLoginRequest = accountLoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountLoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.accountLoginResponse accountLoginResponse;
        
        public accountLoginResponse1() {
        }
        
        public accountLoginResponse1(AccountUtil.AccountService.accountLoginResponse accountLoginResponse) {
            this.accountLoginResponse = accountLoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class chargedProductRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ChargedProductInfo chargedProductRequestInfoField;
        
        /// <remarks/>
        public ChargedProductInfo chargedProductRequestInfo {
            get {
                return this.chargedProductRequestInfoField;
            }
            set {
                this.chargedProductRequestInfoField = value;
                this.RaisePropertyChanged("chargedProductRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class chargedProductResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ChargedProductResultInfo chargedProductResponseInfoField;
        
        /// <remarks/>
        public ChargedProductResultInfo chargedProductResponseInfo {
            get {
                return this.chargedProductResponseInfoField;
            }
            set {
                this.chargedProductResponseInfoField = value;
                this.RaisePropertyChanged("chargedProductResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class chargedProductRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.chargedProductRequest chargedProductRequest;
        
        public chargedProductRequest1() {
        }
        
        public chargedProductRequest1(AccountUtil.AccountService.chargedProductRequest chargedProductRequest) {
            this.chargedProductRequest = chargedProductRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class chargedProductResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.chargedProductResponse chargedProductResponse;
        
        public chargedProductResponse1() {
        }
        
        public chargedProductResponse1(AccountUtil.AccountService.chargedProductResponse chargedProductResponse) {
            this.chargedProductResponse = chargedProductResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class activationLoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AcvLoginInfo acvLoginRequestInfoField;
        
        /// <remarks/>
        public AcvLoginInfo acvLoginRequestInfo {
            get {
                return this.acvLoginRequestInfoField;
            }
            set {
                this.acvLoginRequestInfoField = value;
                this.RaisePropertyChanged("acvLoginRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class activationLoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AcvResultLoginInfo acvLoginResponseInfoField;
        
        /// <remarks/>
        public AcvResultLoginInfo acvLoginResponseInfo {
            get {
                return this.acvLoginResponseInfoField;
            }
            set {
                this.acvLoginResponseInfoField = value;
                this.RaisePropertyChanged("acvLoginResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activationLoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.activationLoginRequest activationLoginRequest;
        
        public activationLoginRequest1() {
        }
        
        public activationLoginRequest1(AccountUtil.AccountService.activationLoginRequest activationLoginRequest) {
            this.activationLoginRequest = activationLoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activationLoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.activationLoginResponse activationLoginResponse;
        
        public activationLoginResponse1() {
        }
        
        public activationLoginResponse1(AccountUtil.AccountService.activationLoginResponse activationLoginResponse) {
            this.activationLoginResponse = activationLoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class dayProductComsumeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DayProductComsumeInfo dayProductComsumeRequestInfoField;
        
        /// <remarks/>
        public DayProductComsumeInfo dayProductComsumeRequestInfo {
            get {
                return this.dayProductComsumeRequestInfoField;
            }
            set {
                this.dayProductComsumeRequestInfoField = value;
                this.RaisePropertyChanged("dayProductComsumeRequestInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cn.jdd/services/account")]
    public partial class dayProductComsumeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DayProductComsumeResultInfo dayProductComsumeResponseInfoField;
        
        /// <remarks/>
        public DayProductComsumeResultInfo dayProductComsumeResponseInfo {
            get {
                return this.dayProductComsumeResponseInfoField;
            }
            set {
                this.dayProductComsumeResponseInfoField = value;
                this.RaisePropertyChanged("dayProductComsumeResponseInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dayProductComsumeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.dayProductComsumeRequest dayProductComsumeRequest;
        
        public dayProductComsumeRequest1() {
        }
        
        public dayProductComsumeRequest1(AccountUtil.AccountService.dayProductComsumeRequest dayProductComsumeRequest) {
            this.dayProductComsumeRequest = dayProductComsumeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dayProductComsumeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cn.jdd/services/account", Order=0)]
        public AccountUtil.AccountService.dayProductComsumeResponse dayProductComsumeResponse;
        
        public dayProductComsumeResponse1() {
        }
        
        public dayProductComsumeResponse1(AccountUtil.AccountService.dayProductComsumeResponse dayProductComsumeResponse) {
            this.dayProductComsumeResponse = dayProductComsumeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ACCOUNTChannel : AccountUtil.AccountService.ACCOUNT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ACCOUNTClient : System.ServiceModel.ClientBase<AccountUtil.AccountService.ACCOUNT>, AccountUtil.AccountService.ACCOUNT {
        
        public ACCOUNTClient() {
        }
        
        public ACCOUNTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ACCOUNTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACCOUNTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACCOUNTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.heartBeatResponse1 AccountUtil.AccountService.ACCOUNT.heartBeat(AccountUtil.AccountService.heartBeatRequest1 request) {
            return base.Channel.heartBeat(request);
        }
        
        public AccountUtil.AccountService.heartBeatResponse heartBeat(AccountUtil.AccountService.heartBeatRequest heartBeatRequest) {
            AccountUtil.AccountService.heartBeatRequest1 inValue = new AccountUtil.AccountService.heartBeatRequest1();
            inValue.heartBeatRequest = heartBeatRequest;
            AccountUtil.AccountService.heartBeatResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).heartBeat(inValue);
            return retVal.heartBeatResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.lastVersionResponse1 AccountUtil.AccountService.ACCOUNT.lastVersion(AccountUtil.AccountService.lastVersionRequest1 request) {
            return base.Channel.lastVersion(request);
        }
        
        public AccountUtil.AccountService.lastVersionResponse lastVersion(AccountUtil.AccountService.lastVersionRequest lastVersionRequest) {
            AccountUtil.AccountService.lastVersionRequest1 inValue = new AccountUtil.AccountService.lastVersionRequest1();
            inValue.lastVersionRequest = lastVersionRequest;
            AccountUtil.AccountService.lastVersionResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).lastVersion(inValue);
            return retVal.lastVersionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.personHeartBeatResponse1 AccountUtil.AccountService.ACCOUNT.personHeartBeat(AccountUtil.AccountService.personHeartBeatRequest1 request) {
            return base.Channel.personHeartBeat(request);
        }
        
        public AccountUtil.AccountService.personHeartBeatResponse personHeartBeat(AccountUtil.AccountService.personHeartBeatRequest personHeartBeatRequest) {
            AccountUtil.AccountService.personHeartBeatRequest1 inValue = new AccountUtil.AccountService.personHeartBeatRequest1();
            inValue.personHeartBeatRequest = personHeartBeatRequest;
            AccountUtil.AccountService.personHeartBeatResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).personHeartBeat(inValue);
            return retVal.personHeartBeatResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.accountLoginResponse1 AccountUtil.AccountService.ACCOUNT.accountLogin(AccountUtil.AccountService.accountLoginRequest1 request) {
            return base.Channel.accountLogin(request);
        }
        
        public AccountUtil.AccountService.accountLoginResponse accountLogin(AccountUtil.AccountService.accountLoginRequest accountLoginRequest) {
            AccountUtil.AccountService.accountLoginRequest1 inValue = new AccountUtil.AccountService.accountLoginRequest1();
            inValue.accountLoginRequest = accountLoginRequest;
            AccountUtil.AccountService.accountLoginResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).accountLogin(inValue);
            return retVal.accountLoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.chargedProductResponse1 AccountUtil.AccountService.ACCOUNT.chargedProduct(AccountUtil.AccountService.chargedProductRequest1 request) {
            return base.Channel.chargedProduct(request);
        }
        
        public AccountUtil.AccountService.chargedProductResponse chargedProduct(AccountUtil.AccountService.chargedProductRequest chargedProductRequest) {
            AccountUtil.AccountService.chargedProductRequest1 inValue = new AccountUtil.AccountService.chargedProductRequest1();
            inValue.chargedProductRequest = chargedProductRequest;
            AccountUtil.AccountService.chargedProductResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).chargedProduct(inValue);
            return retVal.chargedProductResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.activationLoginResponse1 AccountUtil.AccountService.ACCOUNT.activationLogin(AccountUtil.AccountService.activationLoginRequest1 request) {
            return base.Channel.activationLogin(request);
        }
        
        public AccountUtil.AccountService.activationLoginResponse activationLogin(AccountUtil.AccountService.activationLoginRequest activationLoginRequest) {
            AccountUtil.AccountService.activationLoginRequest1 inValue = new AccountUtil.AccountService.activationLoginRequest1();
            inValue.activationLoginRequest = activationLoginRequest;
            AccountUtil.AccountService.activationLoginResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).activationLogin(inValue);
            return retVal.activationLoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountUtil.AccountService.dayProductComsumeResponse1 AccountUtil.AccountService.ACCOUNT.dayProductComsume(AccountUtil.AccountService.dayProductComsumeRequest1 request) {
            return base.Channel.dayProductComsume(request);
        }
        
        public AccountUtil.AccountService.dayProductComsumeResponse dayProductComsume(AccountUtil.AccountService.dayProductComsumeRequest dayProductComsumeRequest) {
            AccountUtil.AccountService.dayProductComsumeRequest1 inValue = new AccountUtil.AccountService.dayProductComsumeRequest1();
            inValue.dayProductComsumeRequest = dayProductComsumeRequest;
            AccountUtil.AccountService.dayProductComsumeResponse1 retVal = ((AccountUtil.AccountService.ACCOUNT)(this)).dayProductComsume(inValue);
            return retVal.dayProductComsumeResponse;
        }
    }
}
